name: Build, Scan, Deploy

on:
    push:
        branches: [main]

permissions:
    id-token: write
    contents: read

jobs:
    build-and-scan:
        runs-on: ubuntu-latest
        outputs:
            image: ${{ steps.vars.outputs.image }}
        steps:
            - uses: actions/checkout@v4

            - id: vars
              run: echo "image=us-central1-docker.pkg.dev/freshcart-twotier/freshcart-repo/checkout-api:${{ github.sha}}" >> "$GITHUB_OUTPUT"

            - name: Build image
              run: docker build -t "${{ steps.vars.outputs.image }}" ./checkout-api

            - name: Scan with Trivy
              uses: aquasecurity/trivy-action@v0.24.0              
              with:
                image-ref: ${{ steps.vars.outputs.image }}
                severity: 'HIGH,CRITICAL'
                exit-code: '1'
                scanners: 'vuln'
                ignore-unfixed: true
                format: 'table'
                trivyignores: checkout-api/.trivyignore

            - name: Authenticate to GCP (WIF)
              uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
                service_account: ${{ vars.GCP_DEPLOY_SA }}

            - name: Configure Docker for Artifact Registry
              run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

            - name: Push image
              run: docker push "${{ steps.vars.outputs.image }}"

    deploy-staging:
        needs: build-and-scan
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - uses: actions/checkout@v4

            - uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
                service_account: ${{ vars.GCP_DEPLOY_SA }}

            - uses: google-github-actions/setup-gcloud@v2

            - name: Deploy to staging
              run: |
                gcloud compute ssh "${{ vars.STAGING_VM_NAME }}" --zone "us-central1-a" --tunnel-through-iap --command="
                  set -e \
                  echo '------- Configuring docker auth -------'
                  gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
                  echo '------- Auth configured, pulling image -------'
                  docker pull ${{ needs.build-and-scan.outputs.image }}
                  docker stop checkout-api || true
                  docker rm checkout-api || true
                  docker run -d --name checkout-api --restart unless-stopped \
                    --network freshcart-net -p 8080:8080 \
                    -e PORT=8080 \
                    -e DATABASE_URL="postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@freshcart-postgres:5432/${{ vars.DB_NAME }}" \
                    ${{ needs.build-and-scan.outputs.image }}
                "

                echo "Deployed ${{needs.build-and-scan.outputs.image }}  to ${{ vars.STAGING_VM_NAME }}"

    deploy-production:
      needs: [build-and-scan, deploy-staging]
      runs-on: ubuntu-latest
      environment: prod
      steps:
            - uses: actions/checkout@v4

            - uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
                service_account: ${{ vars.GCP_DEPLOY_SA }}

            - uses: google-github-actions/setup-gcloud@v2

            - name: Deploy to production
              run: |
                gcloud compute ssh "${{ vars.PROD_VM_NAME }}" --zone "${{ vars.PROD_VM_ZONE }}" --tunnel-through-iap --command="
                  set -e
                  gcloud auth configure-docker us-central1-docker.pkg.dev --quiet && \
                  docker pull ${{ needs.build-and-scan.outputs.image }}
                  docker stop checkout-api || true && \
                  docker rm checkout-api || true && \
                  docker run -d --name checkout-api --restart unless-stopped \
                    --network freshcart-net -p 8080:8080 \
                    -e PORT=8080 \
                    -e DATABASE_URL="postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@freshcart-postgres:5432/${{ vars.DB_NAME }}" \
                    ${{ needs.build-and-scan.outputs.image }}
                "

                echo "Deployed ${{needs.build-and-scan.outputs.image }} to ${{ vars.PROD_VM_NAME }}"


